# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChatApp
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'ChatAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ChatApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChatApp-tvOS

  target 'ChatApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
